# radio_model_lookup.py
"""
Drop-in replacement for RadioMapModelNN that serves radio maps from a
precomputed numpy array (generated by examples/precompute_radio_maps.py)
instead of running neural-network inference.

Array layout (shape 256×256×256×256, dtype float16):
    maps[tx_y, tx_x, :, :]  →  256×256 dBm signal map for TX at pixel (tx_x, tx_y)

Lookup is pure numpy indexing → microseconds per call vs ~1 s for NN.
"""

import numpy as np
from typing import List, Tuple

from .radio_model_nn import RadioMapModelNN


class RadioMapModelLookup(RadioMapModelNN):
    """
    Serves precomputed radio maps from a memory-mapped numpy file.

    Key optimisations vs the naive approach:
    - get_signal_strength: reads a single float16 element instead of loading
      the full 256×256 map (eliminates the dominant astype bottleneck).
    - generate_map: caches converted float32 maps within a step so repeated
      calls for the same TX position pay the astype cost only once.
    """

    def __init__(self,
                 maps_path: str,
                 heightmap: np.ndarray,
                 env_width: float = 256,
                 env_height: float = 256):
        super().__init__(
            model_paths={},
            heightmap=heightmap,
            env_width=env_width,
            env_height=env_height,
            dummy_mode=True,
        )
        self.dummy_mode = False
        self.maps_path  = maps_path
        self._maps      = None
        self._map_cache: dict = {}   # (tx_y, tx_x) → float32 array, cleared each step

    # ------------------------------------------------------------------
    # Lazy loading (safe across Ray fork/spawn)
    # ------------------------------------------------------------------

    @property
    def maps(self) -> np.ndarray:
        if self._maps is None:
            self._maps = np.load(self.maps_path, mmap_mode="r")
        return self._maps

    def clear_cache(self):
        """Call at the start of each env step to drop stale cached maps."""
        self._map_cache.clear()

    # ------------------------------------------------------------------
    # Core overrides
    # ------------------------------------------------------------------

    def generate_map(self,
                     tx_pos: Tuple[float, float],
                     frequency: str) -> np.ndarray:
        """Return precomputed 256×256 dBm map for TX at tx_pos (cached per step)."""
        tx_x = int(round(np.clip(tx_pos[0], 0, self.width  - 1)))
        tx_y = int(round(np.clip(tx_pos[1], 0, self.height - 1)))
        key = (tx_y, tx_x)
        if key not in self._map_cache:
            self._map_cache[key] = self.maps[tx_y, tx_x].astype(np.float32)
        return self._map_cache[key]

    def generate_map_batch(self,
                           tx_positions: List[Tuple[float, float]],
                           frequency: str) -> np.ndarray:
        """Return stack of precomputed maps for a list of TX positions."""
        return np.array([self.generate_map(pos, frequency)
                         for pos in tx_positions], dtype=np.float32)

    def get_signal_strength(self,
                            origin_x: float, origin_y: float,
                            target_x: float, target_y: float,
                            _freq: str = '5.8') -> float:
        """Read a single dBm value directly — no full-map load needed."""
        tx_x = int(round(np.clip(target_x, 0, self.width  - 1)))
        tx_y = int(round(np.clip(target_y, 0, self.height - 1)))
        rx_x = int(round(np.clip(origin_x, 0, self.width  - 1)))
        rx_y = int(round(np.clip(origin_y, 0, self.height - 1)))
        return float(self.maps[tx_y, tx_x, rx_y, rx_x])